import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Michée Allidjinou</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-8">
        <div className="flex flex-col py-20">
          <h1 className="text-2xl font-mono">I build web applications.</h1>
          <h2 className="text-xl text-slate-500">
            michée allidjinou - IT Engineer
          </h2>
        </div>
        <div className="flex flex-col gap-8">
          <h2 className="text-xl font-mono text-red-400">
            michee.projects.list()
          </h2>
          <div className="p-3 bg-slate-300 drop-shadow-sm rounded-sm transition-all duration-200 hover:-translate-y-4">
            <h3 className="font-bold">Chang et Robert</h3>
            <p>
              Implémentation de l'algorithme de Chang et Robert en python.
              L'algorithme permet d'élire un processus dans un système
              distribué.
            </p>
            <a
              href="https://github.com/yoshua70/ChangEtRobert.git"
              target="_blank"
              className="underline"
            >
              Voir sur Github.
            </a>
          </div>
          <div className="bg-slate-300 p-3 drop-shadow-sm rounded-sm transition-all duration-200 hover:-translate-y-4">
            <h3 className="font-bold">API avaxnews</h3>
            <p>
              API de webscrapping pour le site{" "}
              <a href="https://avaxnews.com">avaxnews</a>. Développé avec
              express et Goolge Puppeteer.
            </p>
            <a
              href="https://github.com/yoshua70/avaxnewsapi.git"
              target="_blank"
              className="underline"
            >
              Voir sur Github.
            </a>
          </div>
          <a href="#">Plus &#8594;</a>
        </div>
        <div>
          <h2 className="text-xl font-mono text-red-400">michee.location()</h2>
          <ul>
            <li className="px-4 py-2 transition-all duration-200 hover:bg-red-300 w-fit">
              <a href="https://github.com/yoshua70">Github</a>
            </li>
            <li className="px-4 py-2 transition-all duration-200 hover:bg-red-300 w-fit">
              <a href="https://linkedin.com/in/micheeallidjinou"> LinkedIn</a>
            </li>
          </ul>
        </div>
        <div>
          <h2 className="text-xl font-mono text-red-400">michee.about</h2>
          <p className="text-slate-500 w-full md:w-1/2">
            Passionate about computer science and programming. Right now I'm
            focused on learning react and building apps with Nextjs.
          </p>
        </div>
      </div>
    </Layout>
  );
};

export default Home;
